//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Raizen.UniCad.SAL.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://easyquerywebservice-dev.raizen.com/wsEasyQueryACS.asmx")]
        public string Raizen_UniCad_SAL_WsEasyquery_wsEasyQueryACS {
            get {
                return ((string)(this["Raizen_UniCad_SAL_WsEasyquery_wsEasyQueryACS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://cpsvsappiq01.cosan.rede:50000/XISOAPAdapter/MessageServlet?senderParty=&se" +
            "nderService=PORTAL_UNICAD&receiverParty=&receiverService=&interface=Veiculo_Out&" +
            "interfaceNamespace=urn%3Aminhati.com.br%2Fv2%2Fportalunicad%2Fveiculo")]
        public string Raizen_UniCad_SAL_WSIntegracaoSAP_Veiculo_OutService {
            get {
                return ((string)(this["Raizen_UniCad_SAL_WSIntegracaoSAP_Veiculo_OutService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://rzvlxcisp1q00.cosan.rede:50200/XISOAPAdapter/MessageServlet?senderParty=&s" +
            "enderService=PORTAL_UNICAD&receiverParty=&receiverService=&interface=Motorista_O" +
            "ut&interfaceNamespace=urn%3Aminhati.com.br%2Fv2%2Fportalunicad%2Fmotorista")]
        public string Raizen_UniCad_SAL_WsIntegracaoSAPMotorista_Motorista_OutService {
            get {
                return ((string)(this["Raizen_UniCad_SAL_WsIntegracaoSAPMotorista_Motorista_OutService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://cpsvsappiq01.cosan.rede:50000/XISOAPAdapter/MessageServlet?senderParty=&se" +
            "nderService=PORTAL_UNICAD&receiverParty=&receiverService=&interface=Cliente_Out&" +
            "interfaceNamespace=urn%3Aminhati.com.br%2Fv2%2Fportalunicad%2Fcliente")]
        public string Raizen_UniCad_SAL_WsConsultarCliente_Cliente_OutService {
            get {
                return ((string)(this["Raizen_UniCad_SAL_WsConsultarCliente_Cliente_OutService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://cpsvsappiq01.cosan.rede:50000/XISOAPAdapter/MessageServlet?senderParty=&se" +
            "nderService=PORTAL_UNICAD&receiverParty=&receiverService=&interface=Fornecedor_O" +
            "ut&interfaceNamespace=urn%3Aminhati.com.br%2Fv2%2Fportalunicad%2Ffornecedor")]
        public string Raizen_UniCad_SAL_WsConsultarFornecedor_Fornecedor_OutService {
            get {
                return ((string)(this["Raizen_UniCad_SAL_WsConsultarFornecedor_Fornecedor_OutService"]));
            }
        }
    }
}
