//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Raizen.UniCad.SAL.WsIntegracaoSAPMotorista {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Motorista_OutBinding", Namespace="urn:minhati.com.br/v2/portalunicad/motorista")]
    public partial class Motorista_OutService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback VincularCliente_SyncOperationCompleted;
        
        private System.Threading.SendOrPostCallback Persistir_SyncOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Motorista_OutService() {
            this.Url = global::Raizen.UniCad.SAL.Properties.Settings.Default.Raizen_UniCad_SAL_WsIntegracaoSAPMotorista_Motorista_OutService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event VincularCliente_SyncCompletedEventHandler VincularCliente_SyncCompleted;
        
        /// <remarks/>
        public event Persistir_SyncCompletedEventHandler Persistir_SyncCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sap.com/xi/WebService/soap1.1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("VincularClienteResponse", Namespace="urn:minhati.com.br/v2/portalunicad/motorista")]
        public VincularClienteResponse VincularCliente_Sync([System.Xml.Serialization.XmlElementAttribute(Namespace="urn:minhati.com.br/v2/portalunicad/motorista")] VincularClienteRequest VincularClienteRequest) {
            object[] results = this.Invoke("VincularCliente_Sync", new object[] {
                        VincularClienteRequest});
            return ((VincularClienteResponse)(results[0]));
        }
        
        /// <remarks/>
        public void VincularCliente_SyncAsync(VincularClienteRequest VincularClienteRequest) {
            this.VincularCliente_SyncAsync(VincularClienteRequest, null);
        }
        
        /// <remarks/>
        public void VincularCliente_SyncAsync(VincularClienteRequest VincularClienteRequest, object userState) {
            if ((this.VincularCliente_SyncOperationCompleted == null)) {
                this.VincularCliente_SyncOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVincularCliente_SyncOperationCompleted);
            }
            this.InvokeAsync("VincularCliente_Sync", new object[] {
                        VincularClienteRequest}, this.VincularCliente_SyncOperationCompleted, userState);
        }
        
        private void OnVincularCliente_SyncOperationCompleted(object arg) {
            if ((this.VincularCliente_SyncCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VincularCliente_SyncCompleted(this, new VincularCliente_SyncCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sap.com/xi/WebService/soap1.1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("PersistirResponse", Namespace="urn:minhati.com.br/portalunicad/motorista")]
        public PersistirResponse Persistir_Sync([System.Xml.Serialization.XmlElementAttribute(Namespace="urn:minhati.com.br/portalunicad/motorista")] PersistirRequest PersistirRequest) {
            object[] results = this.Invoke("Persistir_Sync", new object[] {
                        PersistirRequest});
            return ((PersistirResponse)(results[0]));
        }
        
        /// <remarks/>
        public void Persistir_SyncAsync(PersistirRequest PersistirRequest) {
            this.Persistir_SyncAsync(PersistirRequest, null);
        }
        
        /// <remarks/>
        public void Persistir_SyncAsync(PersistirRequest PersistirRequest, object userState) {
            if ((this.Persistir_SyncOperationCompleted == null)) {
                this.Persistir_SyncOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPersistir_SyncOperationCompleted);
            }
            this.InvokeAsync("Persistir_Sync", new object[] {
                        PersistirRequest}, this.Persistir_SyncOperationCompleted, userState);
        }
        
        private void OnPersistir_SyncOperationCompleted(object arg) {
            if ((this.Persistir_SyncCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Persistir_SyncCompleted(this, new Persistir_SyncCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:minhati.com.br/v2/portalunicad/motorista")]
    public partial class VincularClienteRequest {
        
        private string ambienteField;
        
        private string idiomaField;
        
        private VincularClienteRequestClienteVeiculo[] clienteVeiculoField;
        
        private VincularClienteRequestClienteMotorista[] clienteMotoristaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Ambiente {
            get {
                return this.ambienteField;
            }
            set {
                this.ambienteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Idioma {
            get {
                return this.idiomaField;
            }
            set {
                this.idiomaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("clienteVeiculo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public VincularClienteRequestClienteVeiculo[] clienteVeiculo {
            get {
                return this.clienteVeiculoField;
            }
            set {
                this.clienteVeiculoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("clienteMotorista", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public VincularClienteRequestClienteMotorista[] clienteMotorista {
            get {
                return this.clienteMotoristaField;
            }
            set {
                this.clienteMotoristaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:minhati.com.br/v2/portalunicad/motorista")]
    public partial class VincularClienteRequestClienteVeiculo {
        
        private string clienteField;
        
        private string veiculoField;
        
        private string canceladoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cliente {
            get {
                return this.clienteField;
            }
            set {
                this.clienteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string veiculo {
            get {
                return this.veiculoField;
            }
            set {
                this.veiculoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cancelado {
            get {
                return this.canceladoField;
            }
            set {
                this.canceladoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:minhati.com.br/portalunicad/motorista")]
    public partial class PersistirResponse {
        
        private PersistirResponseItem[] mOTORISTAField;
        
        private PersistirResponseItem1[] mOTORISTA_ARField;
        
        private PersistirResponseItem2[] mOTORISTA_EABField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public PersistirResponseItem[] MOTORISTA {
            get {
                return this.mOTORISTAField;
            }
            set {
                this.mOTORISTAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public PersistirResponseItem1[] MOTORISTA_AR {
            get {
                return this.mOTORISTA_ARField;
            }
            set {
                this.mOTORISTA_ARField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public PersistirResponseItem2[] MOTORISTA_EAB {
            get {
                return this.mOTORISTA_EABField;
            }
            set {
                this.mOTORISTA_EABField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:minhati.com.br/portalunicad/motorista")]
    public partial class PersistirResponseItem {
        
        private string cPFField;
        
        private string mSGTYPField;
        
        private string mESSAGEField;
        
        private string rELCUROPDERField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CPF {
            get {
                return this.cPFField;
            }
            set {
                this.cPFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MSGTYP {
            get {
                return this.mSGTYPField;
            }
            set {
                this.mSGTYPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MESSAGE {
            get {
                return this.mESSAGEField;
            }
            set {
                this.mESSAGEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RELCUROPDER {
            get {
                return this.rELCUROPDERField;
            }
            set {
                this.rELCUROPDERField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:minhati.com.br/portalunicad/motorista")]
    public partial class PersistirResponseItem1 {
        
        private string cONDUCTORField;
        
        private string mSGTYPField;
        
        private string mESSAGEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CONDUCTOR {
            get {
                return this.cONDUCTORField;
            }
            set {
                this.cONDUCTORField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MSGTYP {
            get {
                return this.mSGTYPField;
            }
            set {
                this.mSGTYPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MESSAGE {
            get {
                return this.mESSAGEField;
            }
            set {
                this.mESSAGEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:minhati.com.br/portalunicad/motorista")]
    public partial class PersistirResponseItem2 {
        
        private string kTOKKField;
        
        private string sTCD2Field;
        
        private string mESSAGE_CHARACField;
        
        private string mSGTYP_CHARACField;
        
        private string mESSAGE_MOTField;
        
        private string mSGTYP_MOTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string KTOKK {
            get {
                return this.kTOKKField;
            }
            set {
                this.kTOKKField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string STCD2 {
            get {
                return this.sTCD2Field;
            }
            set {
                this.sTCD2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MESSAGE_CHARAC {
            get {
                return this.mESSAGE_CHARACField;
            }
            set {
                this.mESSAGE_CHARACField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MSGTYP_CHARAC {
            get {
                return this.mSGTYP_CHARACField;
            }
            set {
                this.mSGTYP_CHARACField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MESSAGE_MOT {
            get {
                return this.mESSAGE_MOTField;
            }
            set {
                this.mESSAGE_MOTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MSGTYP_MOT {
            get {
                return this.mSGTYP_MOTField;
            }
            set {
                this.mSGTYP_MOTField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:minhati.com.br/portalunicad/motorista")]
    public partial class PersistirRequest {
        
        private string ambienteField;
        
        private string idiomaField;
        
        private PersistirRequestItem[] mOTORISTAField;
        
        private PersistirRequestItem1[] mOTORISTAXField;
        
        private PersistirRequestItem2[] mOTORISTA_EABField;
        
        private PersistirRequestItem3[] mOTORISTAX_EABField;
        
        private PersistirRequestItem4[] mOTORISTA_ARField;
        
        private PersistirRequestItem5[] mOTORISTAX_ARField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Ambiente {
            get {
                return this.ambienteField;
            }
            set {
                this.ambienteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Idioma {
            get {
                return this.idiomaField;
            }
            set {
                this.idiomaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public PersistirRequestItem[] MOTORISTA {
            get {
                return this.mOTORISTAField;
            }
            set {
                this.mOTORISTAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public PersistirRequestItem1[] MOTORISTAX {
            get {
                return this.mOTORISTAXField;
            }
            set {
                this.mOTORISTAXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public PersistirRequestItem2[] MOTORISTA_EAB {
            get {
                return this.mOTORISTA_EABField;
            }
            set {
                this.mOTORISTA_EABField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public PersistirRequestItem3[] MOTORISTAX_EAB {
            get {
                return this.mOTORISTAX_EABField;
            }
            set {
                this.mOTORISTAX_EABField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public PersistirRequestItem4[] MOTORISTA_AR {
            get {
                return this.mOTORISTA_ARField;
            }
            set {
                this.mOTORISTA_ARField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public PersistirRequestItem5[] MOTORISTAX_AR {
            get {
                return this.mOTORISTAX_ARField;
            }
            set {
                this.mOTORISTAX_ARField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:minhati.com.br/portalunicad/motorista")]
    public partial class PersistirRequestItem {
        
        private string tPOPERField;
        
        private string cPFField;
        
        private string nOMEField;
        
        private string sTATUSField;
        
        private string dATANASCField;
        
        private string lIFNRField;
        
        private string kUNNRField;
        
        private string cNHField;
        
        private string cATEGORIAField;
        
        private string vALIDADEField;
        
        private string vALMOPEField;
        
        private string rELCUROPDERField;
        
        private string eXAMEMEDField;
        
        private string rgField;
        
        private string eXPEDIDORField;
        
        private string tELEFONEField;
        
        private string zVALCDDSField;
        
        private string yANR35Field;
        
        private string yANR20Field;
        
        private string eMAILField;
        
        private string tIMTRMField;
        
        private string eXAMEPSIField;
        
        private string rELCURDIRDEFField;
        
        private string mSGTYPField;
        
        private string mESSAGEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TPOPER {
            get {
                return this.tPOPERField;
            }
            set {
                this.tPOPERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CPF {
            get {
                return this.cPFField;
            }
            set {
                this.cPFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NOME {
            get {
                return this.nOMEField;
            }
            set {
                this.nOMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string STATUS {
            get {
                return this.sTATUSField;
            }
            set {
                this.sTATUSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DATANASC {
            get {
                return this.dATANASCField;
            }
            set {
                this.dATANASCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LIFNR {
            get {
                return this.lIFNRField;
            }
            set {
                this.lIFNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string KUNNR {
            get {
                return this.kUNNRField;
            }
            set {
                this.kUNNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CNH {
            get {
                return this.cNHField;
            }
            set {
                this.cNHField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CATEGORIA {
            get {
                return this.cATEGORIAField;
            }
            set {
                this.cATEGORIAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VALIDADE {
            get {
                return this.vALIDADEField;
            }
            set {
                this.vALIDADEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VALMOPE {
            get {
                return this.vALMOPEField;
            }
            set {
                this.vALMOPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RELCUROPDER {
            get {
                return this.rELCUROPDERField;
            }
            set {
                this.rELCUROPDERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EXAMEMED {
            get {
                return this.eXAMEMEDField;
            }
            set {
                this.eXAMEMEDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RG {
            get {
                return this.rgField;
            }
            set {
                this.rgField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EXPEDIDOR {
            get {
                return this.eXPEDIDORField;
            }
            set {
                this.eXPEDIDORField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TELEFONE {
            get {
                return this.tELEFONEField;
            }
            set {
                this.tELEFONEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZVALCDDS {
            get {
                return this.zVALCDDSField;
            }
            set {
                this.zVALCDDSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string YANR35 {
            get {
                return this.yANR35Field;
            }
            set {
                this.yANR35Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string YANR20 {
            get {
                return this.yANR20Field;
            }
            set {
                this.yANR20Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EMAIL {
            get {
                return this.eMAILField;
            }
            set {
                this.eMAILField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TIMTRM {
            get {
                return this.tIMTRMField;
            }
            set {
                this.tIMTRMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EXAMEPSI {
            get {
                return this.eXAMEPSIField;
            }
            set {
                this.eXAMEPSIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RELCURDIRDEF {
            get {
                return this.rELCURDIRDEFField;
            }
            set {
                this.rELCURDIRDEFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MSGTYP {
            get {
                return this.mSGTYPField;
            }
            set {
                this.mSGTYPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MESSAGE {
            get {
                return this.mESSAGEField;
            }
            set {
                this.mESSAGEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:minhati.com.br/portalunicad/motorista")]
    public partial class PersistirRequestItem1 {
        
        private string tPOPERField;
        
        private string cPFField;
        
        private string nOMEField;
        
        private string sTATUSField;
        
        private string dATANASCField;
        
        private string lIFNRField;
        
        private string kUNNRField;
        
        private string cNHField;
        
        private string cATEGORIAField;
        
        private string vALIDADEField;
        
        private string vALMOPEField;
        
        private string rELCUROPDERField;
        
        private string eXAMEMEDField;
        
        private string rgField;
        
        private string eXPEDIDORField;
        
        private string tELEFONEField;
        
        private string zVALCDDSField;
        
        private string yANR35Field;
        
        private string yANR20Field;
        
        private string eMAILField;
        
        private string tIMTRMField;
        
        private string eXAMEPSIField;
        
        private string rELCURDIRDEFField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TPOPER {
            get {
                return this.tPOPERField;
            }
            set {
                this.tPOPERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CPF {
            get {
                return this.cPFField;
            }
            set {
                this.cPFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NOME {
            get {
                return this.nOMEField;
            }
            set {
                this.nOMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string STATUS {
            get {
                return this.sTATUSField;
            }
            set {
                this.sTATUSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DATANASC {
            get {
                return this.dATANASCField;
            }
            set {
                this.dATANASCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LIFNR {
            get {
                return this.lIFNRField;
            }
            set {
                this.lIFNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string KUNNR {
            get {
                return this.kUNNRField;
            }
            set {
                this.kUNNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CNH {
            get {
                return this.cNHField;
            }
            set {
                this.cNHField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CATEGORIA {
            get {
                return this.cATEGORIAField;
            }
            set {
                this.cATEGORIAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VALIDADE {
            get {
                return this.vALIDADEField;
            }
            set {
                this.vALIDADEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VALMOPE {
            get {
                return this.vALMOPEField;
            }
            set {
                this.vALMOPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RELCUROPDER {
            get {
                return this.rELCUROPDERField;
            }
            set {
                this.rELCUROPDERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EXAMEMED {
            get {
                return this.eXAMEMEDField;
            }
            set {
                this.eXAMEMEDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RG {
            get {
                return this.rgField;
            }
            set {
                this.rgField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EXPEDIDOR {
            get {
                return this.eXPEDIDORField;
            }
            set {
                this.eXPEDIDORField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TELEFONE {
            get {
                return this.tELEFONEField;
            }
            set {
                this.tELEFONEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZVALCDDS {
            get {
                return this.zVALCDDSField;
            }
            set {
                this.zVALCDDSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string YANR35 {
            get {
                return this.yANR35Field;
            }
            set {
                this.yANR35Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string YANR20 {
            get {
                return this.yANR20Field;
            }
            set {
                this.yANR20Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EMAIL {
            get {
                return this.eMAILField;
            }
            set {
                this.eMAILField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TIMTRM {
            get {
                return this.tIMTRMField;
            }
            set {
                this.tIMTRMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EXAMEPSI {
            get {
                return this.eXAMEPSIField;
            }
            set {
                this.eXAMEPSIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RELCURDIRDEF {
            get {
                return this.rELCURDIRDEFField;
            }
            set {
                this.rELCURDIRDEFField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:minhati.com.br/portalunicad/motorista")]
    public partial class PersistirRequestItem2 {
        
        private string tPOPERField;
        
        private string kTOKKField;
        
        private string sTCD2Field;
        
        private string nAMEField;
        
        private string sTCD3Field;
        
        private string sTCD4Field;
        
        private string sTKZUField;
        
        private string nAME3Field;
        
        private string nAME4Field;
        
        private string tELF1Field;
        
        private string sORT1Field;
        
        private string sMTP_ADDRField;
        
        private string vCTO_CNHField;
        
        private string vCTO_MOPEField;
        
        private string vCTO_NR20Field;
        
        private string vCTO_NR35Field;
        
        private string vCTO_CARREG_MOTORISTAField;
        
        private string vCTO_TREIN_MOTORISTAField;
        
        private string dATA_NASCIMENTOField;
        
        private string mSGTYP_MOTField;
        
        private string mESSAGE_MOTField;
        
        private string mSGTYP_CHARACField;
        
        private string mESSAGE_CHARACField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TPOPER {
            get {
                return this.tPOPERField;
            }
            set {
                this.tPOPERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string KTOKK {
            get {
                return this.kTOKKField;
            }
            set {
                this.kTOKKField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string STCD2 {
            get {
                return this.sTCD2Field;
            }
            set {
                this.sTCD2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NAME {
            get {
                return this.nAMEField;
            }
            set {
                this.nAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string STCD3 {
            get {
                return this.sTCD3Field;
            }
            set {
                this.sTCD3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string STCD4 {
            get {
                return this.sTCD4Field;
            }
            set {
                this.sTCD4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string STKZU {
            get {
                return this.sTKZUField;
            }
            set {
                this.sTKZUField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NAME3 {
            get {
                return this.nAME3Field;
            }
            set {
                this.nAME3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NAME4 {
            get {
                return this.nAME4Field;
            }
            set {
                this.nAME4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TELF1 {
            get {
                return this.tELF1Field;
            }
            set {
                this.tELF1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SORT1 {
            get {
                return this.sORT1Field;
            }
            set {
                this.sORT1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SMTP_ADDR {
            get {
                return this.sMTP_ADDRField;
            }
            set {
                this.sMTP_ADDRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VCTO_CNH {
            get {
                return this.vCTO_CNHField;
            }
            set {
                this.vCTO_CNHField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VCTO_MOPE {
            get {
                return this.vCTO_MOPEField;
            }
            set {
                this.vCTO_MOPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VCTO_NR20 {
            get {
                return this.vCTO_NR20Field;
            }
            set {
                this.vCTO_NR20Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VCTO_NR35 {
            get {
                return this.vCTO_NR35Field;
            }
            set {
                this.vCTO_NR35Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VCTO_CARREG_MOTORISTA {
            get {
                return this.vCTO_CARREG_MOTORISTAField;
            }
            set {
                this.vCTO_CARREG_MOTORISTAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VCTO_TREIN_MOTORISTA {
            get {
                return this.vCTO_TREIN_MOTORISTAField;
            }
            set {
                this.vCTO_TREIN_MOTORISTAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DATA_NASCIMENTO {
            get {
                return this.dATA_NASCIMENTOField;
            }
            set {
                this.dATA_NASCIMENTOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MSGTYP_MOT {
            get {
                return this.mSGTYP_MOTField;
            }
            set {
                this.mSGTYP_MOTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MESSAGE_MOT {
            get {
                return this.mESSAGE_MOTField;
            }
            set {
                this.mESSAGE_MOTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MSGTYP_CHARAC {
            get {
                return this.mSGTYP_CHARACField;
            }
            set {
                this.mSGTYP_CHARACField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MESSAGE_CHARAC {
            get {
                return this.mESSAGE_CHARACField;
            }
            set {
                this.mESSAGE_CHARACField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:minhati.com.br/portalunicad/motorista")]
    public partial class PersistirRequestItem3 {
        
        private string tPOPERField;
        
        private string sTCD2Field;
        
        private string nAMEField;
        
        private string sORT1Field;
        
        private string sTCD3Field;
        
        private string sTCD4Field;
        
        private string sTKZUField;
        
        private string vCTO_CNHField;
        
        private string vCTO_MOPEField;
        
        private string vCTO_NR20Field;
        
        private string vCTO_NR35Field;
        
        private string vCTO_CARREG_MOTORISTAField;
        
        private string vCTO_TREIN_MOTORISTAField;
        
        private string dATA_NASCIMENTOField;
        
        private string nAME3Field;
        
        private string nAME4Field;
        
        private string sMTP_ADDRField;
        
        private string tELF1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TPOPER {
            get {
                return this.tPOPERField;
            }
            set {
                this.tPOPERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string STCD2 {
            get {
                return this.sTCD2Field;
            }
            set {
                this.sTCD2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NAME {
            get {
                return this.nAMEField;
            }
            set {
                this.nAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SORT1 {
            get {
                return this.sORT1Field;
            }
            set {
                this.sORT1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string STCD3 {
            get {
                return this.sTCD3Field;
            }
            set {
                this.sTCD3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string STCD4 {
            get {
                return this.sTCD4Field;
            }
            set {
                this.sTCD4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string STKZU {
            get {
                return this.sTKZUField;
            }
            set {
                this.sTKZUField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VCTO_CNH {
            get {
                return this.vCTO_CNHField;
            }
            set {
                this.vCTO_CNHField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VCTO_MOPE {
            get {
                return this.vCTO_MOPEField;
            }
            set {
                this.vCTO_MOPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VCTO_NR20 {
            get {
                return this.vCTO_NR20Field;
            }
            set {
                this.vCTO_NR20Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VCTO_NR35 {
            get {
                return this.vCTO_NR35Field;
            }
            set {
                this.vCTO_NR35Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VCTO_CARREG_MOTORISTA {
            get {
                return this.vCTO_CARREG_MOTORISTAField;
            }
            set {
                this.vCTO_CARREG_MOTORISTAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VCTO_TREIN_MOTORISTA {
            get {
                return this.vCTO_TREIN_MOTORISTAField;
            }
            set {
                this.vCTO_TREIN_MOTORISTAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DATA_NASCIMENTO {
            get {
                return this.dATA_NASCIMENTOField;
            }
            set {
                this.dATA_NASCIMENTOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NAME3 {
            get {
                return this.nAME3Field;
            }
            set {
                this.nAME3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NAME4 {
            get {
                return this.nAME4Field;
            }
            set {
                this.nAME4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SMTP_ADDR {
            get {
                return this.sMTP_ADDRField;
            }
            set {
                this.sMTP_ADDRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TELF1 {
            get {
                return this.tELF1Field;
            }
            set {
                this.tELF1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:minhati.com.br/portalunicad/motorista")]
    public partial class PersistirRequestItem4 {
        
        private string tPOPERField;
        
        private string cONDUCTORField;
        
        private string sTATUSField;
        
        private string tARJETA_ACCESOField;
        
        private string aPELLIDOField;
        
        private string nOMBREField;
        
        private string mODO_ENTREGAField;
        
        private string tIPO_NEGOCIOField;
        
        private string cOD_TRANSPORTISTAField;
        
        private string lIC_NAC_CONDField;
        
        private string lIC_NAC_HABILField;
        
        private string vCTO_LIC_NAC_CONDField;
        
        private string vCTO_LIC_NAC_HABILField;
        
        private string vCTO_ART_POLIZAField;
        
        private string vCTO_ART_CUOTAField;
        
        private string vCTO_SEG_VIDA_POLField;
        
        private string vCTO_SEG_VIDA_CUOField;
        
        private string vCTO_SSMA_MAN_DEFField;
        
        private string vCTO_SSMA_RESPEMEField;
        
        private string vCTO_SSMA_POLITICAField;
        
        private string vCTO_TRABAJO_ALTUField;
        
        private string mSGTYPField;
        
        private string mESSAGEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TPOPER {
            get {
                return this.tPOPERField;
            }
            set {
                this.tPOPERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CONDUCTOR {
            get {
                return this.cONDUCTORField;
            }
            set {
                this.cONDUCTORField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string STATUS {
            get {
                return this.sTATUSField;
            }
            set {
                this.sTATUSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TARJETA_ACCESO {
            get {
                return this.tARJETA_ACCESOField;
            }
            set {
                this.tARJETA_ACCESOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string APELLIDO {
            get {
                return this.aPELLIDOField;
            }
            set {
                this.aPELLIDOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NOMBRE {
            get {
                return this.nOMBREField;
            }
            set {
                this.nOMBREField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MODO_ENTREGA {
            get {
                return this.mODO_ENTREGAField;
            }
            set {
                this.mODO_ENTREGAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TIPO_NEGOCIO {
            get {
                return this.tIPO_NEGOCIOField;
            }
            set {
                this.tIPO_NEGOCIOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string COD_TRANSPORTISTA {
            get {
                return this.cOD_TRANSPORTISTAField;
            }
            set {
                this.cOD_TRANSPORTISTAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LIC_NAC_COND {
            get {
                return this.lIC_NAC_CONDField;
            }
            set {
                this.lIC_NAC_CONDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LIC_NAC_HABIL {
            get {
                return this.lIC_NAC_HABILField;
            }
            set {
                this.lIC_NAC_HABILField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VCTO_LIC_NAC_COND {
            get {
                return this.vCTO_LIC_NAC_CONDField;
            }
            set {
                this.vCTO_LIC_NAC_CONDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VCTO_LIC_NAC_HABIL {
            get {
                return this.vCTO_LIC_NAC_HABILField;
            }
            set {
                this.vCTO_LIC_NAC_HABILField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VCTO_ART_POLIZA {
            get {
                return this.vCTO_ART_POLIZAField;
            }
            set {
                this.vCTO_ART_POLIZAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VCTO_ART_CUOTA {
            get {
                return this.vCTO_ART_CUOTAField;
            }
            set {
                this.vCTO_ART_CUOTAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VCTO_SEG_VIDA_POL {
            get {
                return this.vCTO_SEG_VIDA_POLField;
            }
            set {
                this.vCTO_SEG_VIDA_POLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VCTO_SEG_VIDA_CUO {
            get {
                return this.vCTO_SEG_VIDA_CUOField;
            }
            set {
                this.vCTO_SEG_VIDA_CUOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VCTO_SSMA_MAN_DEF {
            get {
                return this.vCTO_SSMA_MAN_DEFField;
            }
            set {
                this.vCTO_SSMA_MAN_DEFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VCTO_SSMA_RESPEME {
            get {
                return this.vCTO_SSMA_RESPEMEField;
            }
            set {
                this.vCTO_SSMA_RESPEMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VCTO_SSMA_POLITICA {
            get {
                return this.vCTO_SSMA_POLITICAField;
            }
            set {
                this.vCTO_SSMA_POLITICAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VCTO_TRABAJO_ALTU {
            get {
                return this.vCTO_TRABAJO_ALTUField;
            }
            set {
                this.vCTO_TRABAJO_ALTUField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MSGTYP {
            get {
                return this.mSGTYPField;
            }
            set {
                this.mSGTYPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MESSAGE {
            get {
                return this.mESSAGEField;
            }
            set {
                this.mESSAGEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:minhati.com.br/portalunicad/motorista")]
    public partial class PersistirRequestItem5 {
        
        private string tPOPERField;
        
        private string cONDUCTORField;
        
        private string sTATUSField;
        
        private string tARJETA_ACCESOField;
        
        private string aPELLIDOField;
        
        private string nOMBREField;
        
        private string mODO_ENTREGAField;
        
        private string tIPO_NEGOCIOField;
        
        private string cOD_TRANSPORTISTAField;
        
        private string lIC_NAC_CONDField;
        
        private string lIC_NAC_HABILField;
        
        private string vCTO_LIC_NAC_CONDField;
        
        private string vCTO_LIC_NAC_HABILField;
        
        private string vCTO_ART_POLIZAField;
        
        private string vCTO_ART_CUOTAField;
        
        private string vCTO_SEG_VIDA_POLField;
        
        private string vCTO_SEG_VIDA_CUOField;
        
        private string vCTO_SSMA_MAN_DEFField;
        
        private string vCTO_SSMA_RESPEMEField;
        
        private string vCTO_SSMA_POLITICAField;
        
        private string vCTO_TRABAJO_ALTUField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TPOPER {
            get {
                return this.tPOPERField;
            }
            set {
                this.tPOPERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CONDUCTOR {
            get {
                return this.cONDUCTORField;
            }
            set {
                this.cONDUCTORField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string STATUS {
            get {
                return this.sTATUSField;
            }
            set {
                this.sTATUSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TARJETA_ACCESO {
            get {
                return this.tARJETA_ACCESOField;
            }
            set {
                this.tARJETA_ACCESOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string APELLIDO {
            get {
                return this.aPELLIDOField;
            }
            set {
                this.aPELLIDOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NOMBRE {
            get {
                return this.nOMBREField;
            }
            set {
                this.nOMBREField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MODO_ENTREGA {
            get {
                return this.mODO_ENTREGAField;
            }
            set {
                this.mODO_ENTREGAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TIPO_NEGOCIO {
            get {
                return this.tIPO_NEGOCIOField;
            }
            set {
                this.tIPO_NEGOCIOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string COD_TRANSPORTISTA {
            get {
                return this.cOD_TRANSPORTISTAField;
            }
            set {
                this.cOD_TRANSPORTISTAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LIC_NAC_COND {
            get {
                return this.lIC_NAC_CONDField;
            }
            set {
                this.lIC_NAC_CONDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LIC_NAC_HABIL {
            get {
                return this.lIC_NAC_HABILField;
            }
            set {
                this.lIC_NAC_HABILField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VCTO_LIC_NAC_COND {
            get {
                return this.vCTO_LIC_NAC_CONDField;
            }
            set {
                this.vCTO_LIC_NAC_CONDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VCTO_LIC_NAC_HABIL {
            get {
                return this.vCTO_LIC_NAC_HABILField;
            }
            set {
                this.vCTO_LIC_NAC_HABILField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VCTO_ART_POLIZA {
            get {
                return this.vCTO_ART_POLIZAField;
            }
            set {
                this.vCTO_ART_POLIZAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VCTO_ART_CUOTA {
            get {
                return this.vCTO_ART_CUOTAField;
            }
            set {
                this.vCTO_ART_CUOTAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VCTO_SEG_VIDA_POL {
            get {
                return this.vCTO_SEG_VIDA_POLField;
            }
            set {
                this.vCTO_SEG_VIDA_POLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VCTO_SEG_VIDA_CUO {
            get {
                return this.vCTO_SEG_VIDA_CUOField;
            }
            set {
                this.vCTO_SEG_VIDA_CUOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VCTO_SSMA_MAN_DEF {
            get {
                return this.vCTO_SSMA_MAN_DEFField;
            }
            set {
                this.vCTO_SSMA_MAN_DEFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VCTO_SSMA_RESPEME {
            get {
                return this.vCTO_SSMA_RESPEMEField;
            }
            set {
                this.vCTO_SSMA_RESPEMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VCTO_SSMA_POLITICA {
            get {
                return this.vCTO_SSMA_POLITICAField;
            }
            set {
                this.vCTO_SSMA_POLITICAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VCTO_TRABAJO_ALTU {
            get {
                return this.vCTO_TRABAJO_ALTUField;
            }
            set {
                this.vCTO_TRABAJO_ALTUField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:minhati.com.br/v2/portalunicad/motorista")]
    public partial class VincularClienteResponse {
        
        private VincularClienteResponseRetornoClienteVeiculo[] retornoClienteVeiculoField;
        
        private VincularClienteResponseRetornoClienteMotorista[] retornoClienteMotoristaField;
        
        private VincularClienteResponseRetornoDadosMotorista[] retornoDadosMotoristaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("retornoClienteVeiculo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public VincularClienteResponseRetornoClienteVeiculo[] retornoClienteVeiculo {
            get {
                return this.retornoClienteVeiculoField;
            }
            set {
                this.retornoClienteVeiculoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("retornoClienteMotorista", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public VincularClienteResponseRetornoClienteMotorista[] retornoClienteMotorista {
            get {
                return this.retornoClienteMotoristaField;
            }
            set {
                this.retornoClienteMotoristaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("retornoDadosMotorista", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public VincularClienteResponseRetornoDadosMotorista[] retornoDadosMotorista {
            get {
                return this.retornoDadosMotoristaField;
            }
            set {
                this.retornoDadosMotoristaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:minhati.com.br/v2/portalunicad/motorista")]
    public partial class VincularClienteResponseRetornoClienteVeiculo {
        
        private string clienteField;
        
        private string veiculoField;
        
        private string mensagemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cliente {
            get {
                return this.clienteField;
            }
            set {
                this.clienteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string veiculo {
            get {
                return this.veiculoField;
            }
            set {
                this.veiculoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string mensagem {
            get {
                return this.mensagemField;
            }
            set {
                this.mensagemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:minhati.com.br/v2/portalunicad/motorista")]
    public partial class VincularClienteResponseRetornoClienteMotorista {
        
        private string clienteField;
        
        private string cpfField;
        
        private string mensagemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cliente {
            get {
                return this.clienteField;
            }
            set {
                this.clienteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cpf {
            get {
                return this.cpfField;
            }
            set {
                this.cpfField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string mensagem {
            get {
                return this.mensagemField;
            }
            set {
                this.mensagemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:minhati.com.br/v2/portalunicad/motorista")]
    public partial class VincularClienteResponseRetornoDadosMotorista {
        
        private string cpfField;
        
        private string nomeMotoristaField;
        
        private string validadeMOPPField;
        
        private string dtTreinamentoNR35Field;
        
        private string dtTreinamentoNR20Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cpf {
            get {
                return this.cpfField;
            }
            set {
                this.cpfField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nomeMotorista {
            get {
                return this.nomeMotoristaField;
            }
            set {
                this.nomeMotoristaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string validadeMOPP {
            get {
                return this.validadeMOPPField;
            }
            set {
                this.validadeMOPPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dtTreinamentoNR35 {
            get {
                return this.dtTreinamentoNR35Field;
            }
            set {
                this.dtTreinamentoNR35Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dtTreinamentoNR20 {
            get {
                return this.dtTreinamentoNR20Field;
            }
            set {
                this.dtTreinamentoNR20Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:minhati.com.br/v2/portalunicad/motorista")]
    public partial class VincularClienteRequestClienteMotorista {
        
        private string clienteField;
        
        private string cpfField;
        
        private string canceladoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cliente {
            get {
                return this.clienteField;
            }
            set {
                this.clienteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cpf {
            get {
                return this.cpfField;
            }
            set {
                this.cpfField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cancelado {
            get {
                return this.canceladoField;
            }
            set {
                this.canceladoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void VincularCliente_SyncCompletedEventHandler(object sender, VincularCliente_SyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VincularCliente_SyncCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VincularCliente_SyncCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public VincularClienteResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((VincularClienteResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void Persistir_SyncCompletedEventHandler(object sender, Persistir_SyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Persistir_SyncCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Persistir_SyncCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PersistirResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PersistirResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591